### ISSUE TITLE
Writing to StatusRegister

### ISSUE THREAD

**Issue by nlsa** [melexis/mlx90640-library#26]
MLX90640_GetFrameData() sets the statusRegister with  MLX90640_I2CWrite(0x8000, 0x0030);   If I read the register immediately, shouldn't its new value be 0x0030?  Mine seems to be stuck at either 0x0008 or 0x0009.  What could cause this?
Thank you -

**Comment by slavysis** [comment]
Sorry for the late reply. Note that the status register is being re-written by the internal MLX90640 electronics in order to represent the current status of the device. As the I2C operations take a lot more time than the internal operations, it is normal to read a value that is different than the one you wrote.
