### ISSUE TITLE
MLX90640_SWI2C_Driver.cpp on STMF437

### ISSUE THREAD

**Issue by nusret103** [melexis/mlx90640-library#50]
Hi,

I have question how I can use this library with a custom pin for SDA and SCL on STM with mbed. We connected the camera on some arbitrary pins for SDA and SCL and when we are trying to print the EEPROM we are getting the 0x0000 values for all memory locations.

Let me know if you have any idea what is happening?

With respect,

Nusret

**Comment by slavysis** [comment]
Hi,

In order to use custom pins, you would most likely need to have a software implementation of the I2C. That means you should indeed use the MLX90640_SWI2C_Driver.cpp. You should simply define the pins with the appropriate names and the what value should be written to the pins in order to get high/low level on the lines. The tricky part would probably be to have the desired clock speed. For that you would need some tool to actually measure the frequency (an oscilloscope would do the job). Once you have this done, all the interface functions are the same as the ones with the hardware I2C implementation. 
Do you think that the information in the MLX90640 driver.pdf on using the software implementation of the I2C is not sufficient?

Best regards
